name: Binaries Windows-2022 (Winlibs)

on:
  workflow_dispatch:
    branches: [ master ]
#env:
#   VERSION: "091224b1"

jobs:
  build:
    runs-on: windows-2022
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}
    steps:
    - uses: actions/checkout@v4
    - name: download winlibs
      shell: cmd
      run: |
        curl -OL https://github.com/brechtsanders/winlibs_mingw/releases/download/12.2.0-16.0.0-10.0.0-ucrt-r5/winlibs-i686-posix-dwarf-gcc-12.2.0-mingw-w64ucrt-10.0.0-r5.zip
        unzip -q winlibs-i686-posix-dwarf-gcc-12.2.0-mingw-w64ucrt-10.0.0-r5.zip
        PATH=%CD%\mingw32\bin;%PATH%
        gcc --version
        curl -OL https://github.com/wmcbrine/PDCurses/archive/refs/tags/3.9.zip
        unzip 3.9.zip
        cd PDCurses-3.9/wincon/
        mingw32-make 
        dir        
        cd ..\..
    - name: compile exe
      shell: cmd
      run: |
        gcc --version
        PATH=%CD%\mingw32\bin;%PATH%
        gcc --version
        cd pexclippy
        mingw32-make winlibs
        dir
    - name: Upload Windows WinlibRelease files
      uses: actions/upload-artifact@v4
      with: 
        name: MicroEmacs09-${{ env.VERSION }}-Windows
        path: MicroEmacs09-${{ env.VERSION }}-Windows
    
    - name: Upload MacOS Release files
      uses: actions/upload-artifact@v4
      with: 
        name: ${{ matrix.os }}-pexclippy-Windows
        path: pexclippy/pexclippy.exe
