name: Binaries MacOS-13,14,15 (macos-gcc)

on:
  workflow_dispatch:
    branches: [ master ]

permissions:
  contents: read
env:
   VERSION: "0.0.1"
   OS: "macos-12"
jobs:
  build:
    strategy:
      matrix:
        os: [macos-13, macos-14, macos-15]  # Specify the MacOS version

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies on MacOS and compile and produce BFS exes and standalone ME application 
        run: |
           echo `uname -a`
           uname -r
           brew install xquartz
           brew install make
           brew install coreutils
           if [[ "${{ matrix.os }}" == "macos-12" ]]; then
              export PATH=/usr/local/opt/make/libexec/gnubin/:$PATH
              export PATH=/usr/local/opt/coreutils/libexec/gnubin:$PATH
              echo "GCC=gcc-12" >> $GITHUB_ENV
           elif [[ "${{ matrix.os }}" == "macos-13" ]]; then
              export PATH=/usr/local/opt/make/libexec/gnubin/:$PATH
              export PATH=/usr/local/opt/coreutils/libexec/gnubin:$PATH
              echo "GCC=gcc-12" >> $GITHUB_ENV
           elif [[ "${{ matrix.os }}" == "macos-13-xlarge" ]]; then
              export PATH=/usr/local/opt/make/libexec/gnubin/:$PATH
              export PATH=/usr/local/opt/coreutils/libexec/gnubin:$PATH
              echo "GCC=gcc-12" >> $GITHUB_ENV
           elif [[ "${{ matrix.os }}" == "macos-14" ]]; then
              export PATH=/opt/homebrew/opt/make/libexec/gnubin:$PATH
              export PATH=/opt/homebrew/opt/coreutils/libexec/gnubin:$PATH
              echo "GCC=gcc-14" >> $GITHUB_ENV
           elif [[ "${{ matrix.os }}" == "macos-15" ]]; then
              export PATH=/opt/homebrew/opt/make/libexec/gnubin:$PATH
              export PATH=/opt/homebrew/opt/coreutils/libexec/gnubin:$PATH
              echo "GCC=gcc-14" >> $GITHUB_ENV
           fi
      - name: Extract branch name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
        
      - name: make macos binary
        run:  |
          cd pexclippy
          make 
          cp pexclippy pexclippy.bin

      - name: Upload MacOS Release files
        uses: actions/upload-artifact@v4
        with: 
          name: ${{ matrix.os }}-pexclippy-MacOS-${{ env.BRANCH_NAME }}
          path: pexclippy/pexclippy.bin
