name: Binaries Ubuntu 22,24 (linux-gcc)

on:
  workflow_dispatch:
    branches: [ master, dev ]
env:
   VERSION: "0.0.1"
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm]  # Specify the Ubuntu version

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: developer library installs
      run: |
        sudo apt install build-essential
        #sudo apt install desktop-file-utils
        sudo apt install libxt-dev
        export ARCH=`hostnamectl  | grep Architecture: | sed -E 's/.+: +//'`
        echo "ARCH=$ARCH" >> $GITHUB_ENV
    - name: make linux binary
      run:  |
        cd pexclippy
        make 
        mkdir bin
        cp pexclippy bin/
        cp ../LICENSE bin/

    - name: Upload Ubuntu Release files
      uses: actions/upload-artifact@v4
      with: 
        name: Linux-${{ env.ARCH }}-pexclippy
        path: pexclippy/pexclippy/bin/*

